= Script for a Reactive To-do app.
Marten Deinum <marten.deinum@conspect.nl>
V1.0, 2017-10-31

:toc:
This contains the script (and code) for the reactive to-do application.

== Setup
First add a `pom.xml` containing the `spring-webflux`, `spring-context`, `reactor-netty` and `jackson-databind` (`gson` would also do). dependencies.


=== Create an "empty" `pom.xml`

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nl.conspect.todo</groupId>
    <artifactId>reactive-todo</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
      <spring.version>5.0.1.RELEASE</spring.version>
      <maven.compiler.source>1.8</maven.compiler.source>
      <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
</project>
----

=== Add Spring Framework BOM
Add, for the easy of use the Spring Framework BOM

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-framework-bom</artifactId>
            <version>${spring.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

=== Add Spring Dependencies

[source,xml]
----
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-context</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-webflux</artifactId>
</dependency>
----

=== Add a runtime
To run the application we will need to add a runtime. Lets add Netty.

[source,xml]
----
<dependency>
    <groupId>io.projectreactor.ipc</groupId>
    <artifactId>reactor-netty</artifactId>
    <version>0.7.1.RELEASE</version>
</dependency>
----

=== Add logback (OPTIONAL)
Additionally you might want to add the `logback-classic` dependency to control the logging.

[source,xml]
----
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.3</version>
</dependency>
----

[source,xml]
----
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%d [%15.15t] %-5p %30.30c %X - %m\n</pattern>
        </encoder>
    </appender>

    <root level="DEBUG">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
----

== Bootstrapping a Reactive Application
To bootstrap an application we would need to create an instance of a container, Netty in this case, and keep it running.

=== Add `TodoApplication` class

[source,java]
----
public class TodoApplication {
  public static void main(String[] args) {
        try (AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(TodoConfiguration.class)) {
            context.getBean(NettyContext.class).onClose().block();
        }
    }

    @Configuration
    @EnableWebFlux
    @ComponentScan
    public static class TodoConfiguration {

      @Bean
      public NettyContext nettyContext(ApplicationContext context) {

          HttpHandler handler = WebHttpHandlerBuilder.applicationContext(context).build();
          ReactorHttpHandlerAdapter adapter = new ReactorHttpHandlerAdapter(handler);
          HttpServer httpServer = HttpServer.create("localhost", 8080);
          return httpServer.newHandler(adapter).block();
      }
  }
}
----

.The `HttpHandler` is the Spring compo
. The `ReactorHttpHandlerAdapter` is the adapter to convert between Netty request/response and the Spring WebFlux components.
. `HttpServer` is the Netty container
. The last line registeres the handler function with the Netty container.

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.9.1</version>
</dependency>
----